 version: 2.1

 orbs:
   heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

 workflows:
   heroku_deploy:
     jobs:
       - heroku/deploy-via-git:
           filters:
             branches:
               only: main # only run deploy-via-git job on main branch